name: deploy
on:
  release:
    types: [ published ]
  push:
    branches: [ desenvolvimento ]
jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
  build:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v3
    -
      name: setup Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
    -
      name: yarn build
      run: |
        yarn ci
        yarn build
    -
      uses: actions/upload-artifact@v3
      with:
        name: yarn-build-artifact
        path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v3
    -
      uses: actions/download-artifact@v3
      with:
        name: yarn-build-artifact
        path: dist/
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to registry.patrick.dev.br
      uses: docker/login-action@v2
      with:
        registry: registry.patrick.dev.br
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    -
      name: Build and push to teste
      uses: docker/build-push-action@v3
      if: github.ref == 'desenvolvimento'
      with:
        file: .devops/docker/Dockerfile
        context: .
        push: true
        tags: registry.patrick.dev.br/almox-web:staging
    -
      name: Build and push to prod
      uses: docker/build-push-action@v3
      if: github.ref == 'master'
      with:
        file: .devops/docker/Dockerfile
        context: .
        push: true
        tags: registry.patrick.dev.br/almox-web:latest
